name: Deploy to GitHub Pages
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - id: node-version
      run: echo "::set-output name=version=$(cat .node-version)"
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.node-version.outputs.version }}
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./dist
